"""initial inventario migration

Revision ID: 8218b31822f3
Revises: 
Create Date: 2024-11-30 17:20:22.528808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8218b31822f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('fecha_transaccion', sa.DateTime(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('entrada_salida', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='inventario'
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='inventario'
    )
    op.drop_table('alembic_version_compras')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version_compras',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_compras_pkc')
    )
    op.drop_table('stock', schema='inventario')
    op.drop_table('movimientos', schema='inventario')
    # ### end Alembic commands ###
